repos:
  - repo: local
    hooks:
      - id: always-pass
        name: Always Pass
        entry: echo "Always pass"
        language: system
        pass_filenames: false
        stages: [ pre-commit ]

#  - repo: local
#    hooks:
#      - id: lint-check
#        name: Run lint check
#        entry: poetry run lint
#        language: system
#        pass_filenames: false
#        stages: [ pre-commit ]
#
#  - repo: local
#    hooks:
#      - id: coverage-check
#        name: Run coverage check
#        entry: poetry run coverage
#        language: system
#        pass_filenames: false
#        stages: [ pre-commit ]
