repos:
  - repo: local
    hooks:
      - id: coverage-check
        name: Run coverage check
        entry: poetry run python -c "from checks import run_coverage; run_coverage()"
        language: system
        pass_filenames: false
        stages: [ pre-push ]

  - repo: local
    hooks:
      - id: lint-check
        name: Run lint check
        entry: poetry run python -c "from checks import run_lint; run_lint()"
        language: system
        pass_filenames: false
        stages: [ pre-push ]
